// <auto-generated />
namespace ComX_0._0._2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class np0206 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(np0206));
        
        string IMigrationMetadata.Id
        {
            get { return "201705270838351_np0206"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
